### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by rijinrij** [PushpenderIndia/subdover#1]
File "subdover.py", line 182, in <module>
    os.rename(f"{arguments.subdomain_list}-httpx.txt", f"{arguments.subdomain_list}")
FileNotFoundError: [Errno 2] No such file or directory: 'example_target.txt-httpx.txt' -> 'example_target.txt'

**Comment by PushpenderIndia** [comment]
Make sure to give full path of subdomainList after --list parameter

**Comment by PushpenderIndia** [comment]
On which system, you are using subdover ?

**Comment by rijinrij** [comment]
Kali on WSL

**Comment by PushpenderIndia** [comment]
Please Clone Latest Edition of Subdover and try again!

Now it should be fixed

**Comment by rijinrij** [comment]
thanks fixed

**Comment by rijinrij** [comment]
root@MrCyguru:/opt/subdover# python3 subdover.py --help
Traceback (most recent call last):
  File "subdover.py", line 1, in <module>
    from src.fingerprints import *
ModuleNotFoundError: No module named 'src.fingerprints'

**Comment by PushpenderIndia** [comment]
Added __init__.py file in src directory, now check again that the issue is solved or not
