### ISSUE TITLE
Why httpx rescan with https list

### ISSUE THREAD

**Issue by blackcodersec** [PushpenderIndia/subdover#14]
I provide httprobe list, but I saw this script again performing with httpx scan.

**Comment by blackcodersec** [comment]
I think you have to need to stop httpx. Users can manually probe with httpx or httprobe. When starting subdover scan it works very slow.

**Comment by blackcodersec** [comment]
When I use `live` file then auto make a file `live_httpx.txt` then when I select `live_httpx.txt` and same auto make a new file `live_httpx.txt_httpx.txt`.
why?

![image](https://user-images.githubusercontent.com/72689232/152338392-21ba987b-9f82-4333-b13f-7f6dd8083ef7.png)

**Comment by PushpenderIndia** [comment]
Update subdover and use `-skip` flag with `-l` or `--list` flag

e.g. `python3 subdover.py --list subdomains.txt -skip`

**Note** : If you use `-skip` flag, then Make sure to manually use httpx/httprobe or any similar tool on your subdomain list before passing it to subdover
