### ISSUE TITLE
updating required

### ISSUE THREAD

**Issue by GDATTACKER-RESEARCHER** [PushpenderIndia/subdover#9]
https://github.com/EdOverflow/can-i-take-over-xyz/issues/170
https://github.com/EdOverflow/can-i-take-over-xyz/issues/167
https://github.com/EdOverflow/can-i-take-over-xyz/issues/183

**Comment by GDATTACKER-RESEARCHER** [comment]
https://github.com/EdOverflow/can-i-take-over-xyz/issues/188

**Comment by PushpenderIndia** [comment]
* Following Fingerprints Added Succcessfully

 - [x]  Appery.io
 - [x] Vercel.com
 - [x] Datocms.com

This was already added : EdOverflow/can-i-take-over-xyz#170

```
f71 =  [
        "Appery.io",
        "Vulnerable",
        [""],  #404 Cname
        "<p>This page will be updated automatically when your app is published.</p>",
        # Pointing to 107.20.248.61
    ]
 
f72 = [
        "Vercel.com",
        "Vulnerable",
        [""], #404 Cname
        "The deployment could not be found on Vercel."
    ]
   
f73 = [
        "Datocms.com",
        "Vulnerable",
        [""], #404 Cname
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>Loading...</title>",
    ]   

```
